CREATE TABLE IF NOT EXISTS financials ( 
    ID                        INTEGER IDENTITY(0,1),
    symbol                    VARCHAR(6),
    fdic_cert_id              INTEGER,
    report_date               DATE,
    type                      VARCHAR(255),
    currency                  VARCHAR(255),
    total_assets              DECIMAL(19,0),
    total_liabilities         DECIMAL(19,0),
    total_shareholder_equity  DECIMAL(19,0),
    total_revenue             DECIMAL(19,0),
    net_income                DECIMAL(19,0),
    gross_profit              DECIMAL(19,0),
    operating_income          DECIMAL(19,0),
    ebit                      DECIMAL(19,0),
    operating_cashflow        DECIMAL(19,0),
    profit_loss               DECIMAL(19,0),
    return_on_assets          DECIMAL(9,6),
    return_on_equity          DECIMAL(9,6),
    efficiency_ratio          DECIMAL(9,6),
    net_interest_margin       DECIMAL(9,6),
    yield_on_earning_assets   DECIMAL(9,6),
    primary key(ID)
);