CREATE TABLE IF NOT EXISTS financials (
    ID                        INTEGER IDENTITY(0,1),
    symbol                    VARCHAR(6),
    report_date               DATE,
    type                      VARCHAR(255),
    currency                  VARCHAR(255),
    total_assets              BIGINT(255),
    total_liabilities         BIGINT(255),
    total_shareholder_equity  BIGINT(255),
    total_revenue             BIGINT(255),
    net_income                BIGINT(255),
    gross_profit              BIGINT(255),
    operating_income          BIGINT(255),
    ebit                      BIGINT(255),
    operating_cashflow        BIGINT(255),
    profit_loss               BIGINT(255),
    return_on_assets          DECIMAL(9,6),
    return_on_equity          DECIMAL(9,6),
    efficiency_ratio          DECIMAL(9,6),
    net_interest_margin       DECIMAL(9,6),
    yield_on_earning_assets   DECIMAL(9,6),
    primary key(ID)
);